# Generated by Django 4.0.3 on 2022-04-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions_data',
            name='major_group_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='专业组代码'),
        ),
    ]
