# Generated by Django 4.0.3 on 2022-04-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yingding', '0002_alter_admissions_data_major_group_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions_data',
            options={'verbose_name': '招生数据'},
        ),
    ]
