# Generated by Django 4.0.3 on 2022-04-03 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yingding', '0003_alter_admissions_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions_data',
            options={},
        ),
    ]
